<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Simpan</name>
   <tag></tag>
   <elementGuidId>07d5663c-25d2-43f2-abfe-6ac20316e1d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[2]/div/div/div[2]/div/div[1]/div/div/div[2]/div/div/div[2]/a[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.mt-2.prosesOrder</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>c0f8a4e4-3c68-4a0e-8abd-3baf7300bc53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bbf3015a-3744-4c97-a6cb-37628e0b4bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary mt-2 prosesOrder</value>
      <webElementGuid>29adb331-0aa8-4f49-a3e7-1ea8373c327f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Simpan</value>
      <webElementGuid>6b4745c5-c533-45e7-904c-fbb476daf84d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancel-row&quot;)/div[@class=&quot;col-xl-12 col-lg-12 col-sm-12  layout-spacing&quot;]/div[@class=&quot;widget-content widget-content-area br-4&quot;]/div[@class=&quot;col-xl-12 col-lg-12 col-md-12&quot;]/div[@class=&quot;statbox box box-shadow&quot;]/div[@class=&quot;row fixed-bottom&quot;]/div[@class=&quot;col-sm-12&quot;]/div[@class=&quot;widget-content widget-content-area&quot;]/div[@class=&quot;float-right&quot;]/a[@class=&quot;btn btn-primary mt-2 prosesOrder&quot;]</value>
      <webElementGuid>5806827a-a722-4ec8-8d4b-94f36b493e50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@type='button'])[3]</value>
      <webElementGuid>4a319138-b5be-403d-bdc1-d0e331e6b8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cancel-row']/div/div/div/div/div[2]/div/div/div[2]/a[2]</value>
      <webElementGuid>890f0895-0d8f-49cd-9b38-8d06881f243d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Simpan')]</value>
      <webElementGuid>015e9468-07b1-486e-b1b0-f4827c960181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah Meja'])[1]/following::a[1]</value>
      <webElementGuid>0e12dcc3-0105-4828-a343-2452e859565f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kembali'])[1]/following::a[2]</value>
      <webElementGuid>ceeb9bfe-f07c-4be2-a8f7-5fb310ba5a19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Simpan &amp; Cetak'])[1]/preceding::a[1]</value>
      <webElementGuid>fdb99071-b14b-422a-acaa-143d3cc83b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ubah Meja'])[2]/preceding::a[2]</value>
      <webElementGuid>b7208ddc-b10c-4cfb-9221-f882e2eeae29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Simpan']/parent::*</value>
      <webElementGuid>13d7486a-43f1-4279-8564-dfb5db1285c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>8ac099e2-fd3b-4a9b-a699-d581be87840c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@type = 'button' and (text() = 'Simpan' or . = 'Simpan')]</value>
      <webElementGuid>c2b14399-898c-4122-a3fe-d3f03a88c3c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
