<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>b0ff7ea8-4f5d-4ef0-8382-340bec440b29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='justify-right-pills-home']/section/div/a/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>a9d55e74-c772-4867-9d1f-6bf6f933c780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>b821c43f-6048-4645-9bfe-41d53d333a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>4df75bb1-128a-4096-a785-47ffd1ee8730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pos.lumintu.xyz/images/fnb.jpg</value>
      <webElementGuid>0b0ffa69-bc1a-4e7b-ac87-5b6a8bdabf2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='https://pos.lumintu.xyz/images/fnb.jpg';</value>
      <webElementGuid>a84db92e-41ef-47bb-bc1b-8d87732365b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;justify-right-pills-home&quot;)/section[@class=&quot;row&quot;]/div[1]/a[@class=&quot;menuCard&quot;]/div[@class=&quot;category-tile&quot;]/img[1]</value>
      <webElementGuid>e6014628-a12d-4ac9-a239-bd6cf35508bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='justify-right-pills-home']/section/div/a/div/img</value>
      <webElementGuid>bf189dbb-783e-4aee-9896-6a208512594b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pos.lumintu.xyz/images/fnb.jpg')]</value>
      <webElementGuid>ef6ae075-f6ab-482b-8f21-31501ffb76a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>bb2fc2b3-3536-43c6-90e0-ac719debcea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pos.lumintu.xyz/images/fnb.jpg']</value>
      <webElementGuid>4625c60b-30f6-4ac8-8537-0b69aee32de9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
