<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dtl0odqty</name>
   <tag></tag>
   <elementGuidId>9d09e1bc-b677-4a3a-b1cf-88afc8adbbe2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='dtl[0][odqty]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;dtl[0][odqty]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8cd931cf-60d2-45a9-8b89-4d6e5724ffb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a4de45c5-d1d8-4177-b3be-826122cf4f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-number subQty</value>
      <webElementGuid>397de710-2056-4b56-92a7-2697fa166833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>bdb4858a-f49b-4e62-9cf7-096d45b55814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dtl[0][odqty]</value>
      <webElementGuid>1e26485b-1230-4c84-a017-cec7c567a08f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detailOrder&quot;)/tbody[1]/tr[@class=&quot;subitem&quot;]/td[@class=&quot;text-center&quot;]/input[@class=&quot;input-number subQty&quot;]</value>
      <webElementGuid>dda56c37-fb4c-4673-b759-d771f992ed38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='dtl[0][odqty]']</value>
      <webElementGuid>c055d81b-b997-40c3-bcb6-ee0735f22fa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='detailOrder']/tbody/tr/td[3]/input</value>
      <webElementGuid>50580970-aaaf-4c05-9d6f-ba7f2332d111</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>31d7a7dd-d56a-4461-a04c-aa2c92332025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'dtl[0][odqty]']</value>
      <webElementGuid>67c1d044-12a6-4f97-9a52-6872bf425f73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
