<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__dtl2odqty</name>
   <tag></tag>
   <elementGuidId>6983475b-6bb5-4fbd-b759-13a3842217a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='dtl[2][odqty]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;dtl[2][odqty]&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89a71689-bdae-4ad8-aa82-b7a5d03ccf73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>36d9a7a9-163a-41c8-b5d7-8b1471faf398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-number subQty</value>
      <webElementGuid>d8d27ea6-49d0-43c5-bc18-af7a24231df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b041480c-71cb-4d1d-8aff-c16d7b239cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>dtl[2][odqty]</value>
      <webElementGuid>c7758e0b-f5c2-43bb-8e31-a11ffe900be4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;detailOrder&quot;)/tbody[1]/tr[@class=&quot;subitem&quot;]/td[@class=&quot;text-center&quot;]/input[@class=&quot;input-number subQty&quot;]</value>
      <webElementGuid>821e4771-9ffb-443c-927f-15fd7bfc35bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='dtl[2][odqty]']</value>
      <webElementGuid>50a24d6f-170f-4923-a47e-f9c7076d15d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='detailOrder']/tbody/tr[3]/td[3]/input</value>
      <webElementGuid>aff1e64e-2ea6-4569-9cb4-3aeaeb4d8584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/input</value>
      <webElementGuid>02090d4d-06bd-4da2-bf6b-2b325b27693e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'dtl[2][odqty]']</value>
      <webElementGuid>e7cfdab1-3566-442e-bc64-118f11d958cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
