<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Buat Baru_feather feather-plus-circle</name>
   <tag></tag>
   <elementGuidId>58c4c89e-1723-4fd9-94cc-9a1d6135704e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Buat Baru'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.feather.feather-plus-circle</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>9b988627-1f95-4839-92cd-4ef5c1e02f8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>85f93537-38b3-46a3-81cc-41fbb7890c06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>204c7da1-4e79-4952-8e98-9ebf84c6fcd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>9e32254e-df9e-42aa-8250-3609912c9d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>80702b9c-d32b-4abd-a276-65866a45cc2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>ac051a8c-b18b-428c-b24c-aa0457e8f8d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>8c3010f4-9726-4364-bbd0-e8f962ca3d5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>af99eca9-e2c5-4fb3-8698-41b331d98edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>2c5545e1-38f3-4fe4-80dc-bce4955d6b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>335a31fe-91fc-4e6f-a276-da142c269a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feather feather-plus-circle</value>
      <webElementGuid>7dab1884-d8a1-476c-a66c-1d7ddb1f70ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancel-row&quot;)/div[@class=&quot;col-xl-12 col-lg-12 col-sm-12  layout-spacing&quot;]/div[@class=&quot;row layout-top-spacing&quot;]/div[@class=&quot;col-xl-3 col-lg-3 col-md-6 col-sm-6 col-12 layout-spacing&quot;]/a[1]/div[@class=&quot;widget widget-card-four&quot;]/div[@class=&quot;widget-content&quot;]/div[@class=&quot;w-content&quot;]/div[2]/div[@class=&quot;w-icon&quot;]/svg[@class=&quot;feather feather-plus-circle&quot;]</value>
      <webElementGuid>1fe9f9d8-3353-491c-a98d-28aa66c30a47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buat Baru'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>72060c64-d1fc-4f9d-9bc3-381e7d4126ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Meja Pesanan'])[2]/following::*[name()='svg'][2]</value>
      <webElementGuid>4956ebd2-b600-41c8-b31c-56752b548f65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dapur'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>680c8cec-b86e-48f1-bd62-b17e18168e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pesanan'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>e9198155-2bae-42ff-baa5-783138d8a6f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
