<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Negative</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d34f375c-bab9-46ed-9a89-5ade8e103a69</testSuiteGuid>
   <testCaseLink>
      <guid>fe81ac18-7aa4-496d-88bf-a3c6ef1090bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tetsing BTN/Negative/Transaksi</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cb16b57c-57d1-4247-81b2-4d9c4431c43a</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Transaksi/Negative</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>cb16b57c-57d1-4247-81b2-4d9c4431c43a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Quantity_Item</value>
         <variableId>f06cb3ad-c4c5-4757-9d89-6823e84ef4ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cb16b57c-57d1-4247-81b2-4d9c4431c43a</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Quantity_Item_1</value>
         <variableId>8ac00a90-0388-4f74-bb19-69ea391dc701</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
