<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Negative</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d34f375c-bab9-46ed-9a89-5ade8e103a69</testSuiteGuid>
   <testCaseLink>
      <guid>cc8cb9d3-14e2-4e24-965e-532d53a0b882</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Tetsing BTN/Negative/Transaksi</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b24a9418-495d-48b7-b62b-f424d9b49a0e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Transaksi/Negative</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b24a9418-495d-48b7-b62b-f424d9b49a0e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>QTY</value>
         <variableId>f06cb3ad-c4c5-4757-9d89-6823e84ef4ab</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b24a9418-495d-48b7-b62b-f424d9b49a0e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>QYT_1</value>
         <variableId>8ac00a90-0388-4f74-bb19-69ea391dc701</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
