<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img - Copy (3)</name>
   <tag></tag>
   <elementGuidId>cbf3bd3c-4ba6-4b78-853b-fd3eeb71f4bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;justify-right-pills-home&quot;]/section[1]/div[5]/a/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>130fe33a-9a92-4db4-90e9-8e3c5aea7482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>c5e70919-24e4-43da-a945-6c71ba4b81af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>7d274529-05a8-4a2d-b34a-c1a1a1d7bb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pos.lumintu.xyz/images/fnb.jpg</value>
      <webElementGuid>9e77a2ba-2c34-40c4-bc36-4b16bf9e3102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='https://pos.lumintu.xyz/images/fnb.jpg';</value>
      <webElementGuid>c9f1617a-202e-4dd5-9da6-d61dd75e7878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;justify-right-pills-home&quot;)/section[@class=&quot;row&quot;]/div[1]/a[@class=&quot;menuCard&quot;]/div[@class=&quot;category-tile&quot;]/img[1]</value>
      <webElementGuid>a21037a1-6ec1-4522-8b95-a2f76edbe520</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='justify-right-pills-home']/section/div/a/div/img</value>
      <webElementGuid>622df523-e9f8-46bd-9e14-e4abaa1d241c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pos.lumintu.xyz/images/fnb.jpg')]</value>
      <webElementGuid>fd5ebf6a-0a6b-4b50-ab18-6efe26eca4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>1d271319-2921-4200-9794-92278f7c274b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pos.lumintu.xyz/images/fnb.jpg']</value>
      <webElementGuid>46b88caf-c0ef-4a6c-b5e7-f849a4de06b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
