<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img - Copy</name>
   <tag></tag>
   <elementGuidId>749cd705-60c6-4f7b-8d89-82a84796ae61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;justify-right-pills-home&quot;]/section[1]/div[2]/a/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>976e2143-ca0d-4c0c-9b0d-a94e5d54bdba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>0cf75ed7-b5d3-48d3-981f-21c63a3a6ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>8ba54193-4e41-4b57-bf70-6dce6dcbc3fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pos.lumintu.xyz/images/fnb.jpg</value>
      <webElementGuid>513704e4-5041-42c6-8bbc-eb9941ad3030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='https://pos.lumintu.xyz/images/fnb.jpg';</value>
      <webElementGuid>f48b1be5-7d85-4add-938a-676b0b86de27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;justify-right-pills-home&quot;)/section[@class=&quot;row&quot;]/div[1]/a[@class=&quot;menuCard&quot;]/div[@class=&quot;category-tile&quot;]/img[1]</value>
      <webElementGuid>e17c5218-7b68-4343-bf6f-2fd1d6d65ecb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='justify-right-pills-home']/section/div/a/div/img</value>
      <webElementGuid>47fb07ca-e57b-43a1-98f0-2a1b01676f62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pos.lumintu.xyz/images/fnb.jpg')]</value>
      <webElementGuid>d6e547d9-709f-41e7-bb9a-e232966058aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>c5a7e0c1-e9f4-4a61-82c8-0819c828fbe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pos.lumintu.xyz/images/fnb.jpg']</value>
      <webElementGuid>a5de06cf-560d-4d2f-9f5b-3c92f779af1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
