<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img - Copy (2)</name>
   <tag></tag>
   <elementGuidId>670c08dd-d2c0-4056-b25f-1a2c2fed4d57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;justify-right-pills-home&quot;]/section[1]/div[4]/a/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e4708cf5-4078-4dc4-95fe-946d86140d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>63c14521-75c6-412b-9e51-4ca6ca3fc181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>aeb4680c-16ab-4b1a-932d-44bdc212c8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pos.lumintu.xyz/images/fnb.jpg</value>
      <webElementGuid>624ac5ea-6c9d-4398-bf96-f5ad25d79799</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='https://pos.lumintu.xyz/images/fnb.jpg';</value>
      <webElementGuid>e0df437b-4cc2-4bce-96d8-69e14780522c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;justify-right-pills-home&quot;)/section[@class=&quot;row&quot;]/div[1]/a[@class=&quot;menuCard&quot;]/div[@class=&quot;category-tile&quot;]/img[1]</value>
      <webElementGuid>1f4331f6-4aee-4b3d-980e-7c52bec6350e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='justify-right-pills-home']/section/div/a/div/img</value>
      <webElementGuid>0384bc1f-1fa4-47e3-96f5-c6f2680d7b31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pos.lumintu.xyz/images/fnb.jpg')]</value>
      <webElementGuid>ffb95158-b1f5-44d1-8c1c-5e0e1225c179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>773d53f4-4e79-4770-bf2a-616984bc1e49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pos.lumintu.xyz/images/fnb.jpg']</value>
      <webElementGuid>cb1ebf13-6b35-45f6-9ad1-25b30d002ee0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
