<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img - Copy (1)</name>
   <tag></tag>
   <elementGuidId>27523680-0102-4d4e-b23c-7fb995a6c306</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;justify-right-pills-home&quot;]/section[1]/div[3]/a/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>724991c5-7948-4997-ab00-8b6c7f0029a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>f0cf83e8-4c71-490a-8e03-0f7ea020ea2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>120</value>
      <webElementGuid>dd0f5a1d-c387-4aec-b770-03d9efa3c42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://pos.lumintu.xyz/images/fnb.jpg</value>
      <webElementGuid>db966afc-89c8-4034-add0-f9180db81ce4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>this.onerror=null;this.src='https://pos.lumintu.xyz/images/fnb.jpg';</value>
      <webElementGuid>c87b77d0-3fd1-46ca-acbf-0c6d71ab3da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;justify-right-pills-home&quot;)/section[@class=&quot;row&quot;]/div[1]/a[@class=&quot;menuCard&quot;]/div[@class=&quot;category-tile&quot;]/img[1]</value>
      <webElementGuid>b9529f91-d372-4013-b67f-de497ae3067f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='justify-right-pills-home']/section/div/a/div/img</value>
      <webElementGuid>6341e303-580e-4d19-a14c-05399aec3afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://pos.lumintu.xyz/images/fnb.jpg')]</value>
      <webElementGuid>a47ecfb5-4dd1-45d5-bb89-66bb3983ed1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>e808fc45-48d8-4b98-b782-0a071af55932</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://pos.lumintu.xyz/images/fnb.jpg']</value>
      <webElementGuid>b10d2fee-2105-48ff-8336-271c0cadb45d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
