<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Masuk</name>
   <tag></tag>
   <elementGuidId>29901f96-e539-4293-a1aa-61c884087f57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@value='']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.btn.btn-primary</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2bd2401e-b0d1-468b-adea-8c464f35de8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>16dd228e-153c-4a35-9f1a-6a8ab528e210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>83f281f0-48d5-4790-bc86-59022b25c108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Masuk</value>
      <webElementGuid>4b9a7ef1-85ba-4195-97c8-2728b5fade22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;form&quot;]/div[@class=&quot;form-container outer&quot;]/div[@class=&quot;form-form&quot;]/div[@class=&quot;form-form-wrap&quot;]/div[@class=&quot;form-container&quot;]/div[@class=&quot;form-content&quot;]/form[@class=&quot;text-left&quot;]/div[@class=&quot;form&quot;]/div[@class=&quot;d-sm-flex justify-content-between&quot;]/div[@class=&quot;field-wrapper&quot;]/button[@class=&quot;btn btn-primary&quot;]</value>
      <webElementGuid>63e48808-4102-4528-8ada-6fc482cbdf08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@value='']</value>
      <webElementGuid>2dd5995e-1a65-4c3f-b782-e17c451bdba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KATA SANDI'])[1]/following::button[1]</value>
      <webElementGuid>453af80f-b261-4dfc-bc48-1847fb357038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USERNAME'])[1]/following::button[1]</value>
      <webElementGuid>0d70da17-8c71-49a5-9952-929b55adbfeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>28847a58-0b97-44b6-a6ac-20e7b88b99fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Masuk' or . = 'Masuk')]</value>
      <webElementGuid>0a61c740-8e41-4096-85d6-5e86f496eb76</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
